# Generated by Django 3.2.6 on 2022-07-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Разместите фото для объявления', null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(help_text='Введите название товара', max_length=200, verbose_name='Название товара'),
        ),
    ]
